final battle

diff --git a/vissh_snap b/vissh_snap
--- a/vissh_snap
+++ b/vissh_snap
@@ -1,18 +1,20 @@
-if [ ! -f $SNAP_REAL_HOME/.vimrc ]; then touch $SNAP_REAL_HOME/.vimrc; fi;
+USER_HOME=/home/${SUDO_USER}
+
+if [ ! -f $USER_HOME/.vimrc ]; then touch $USER_HOME/.vimrc; fi;
 echo "$SNAL_REAL_HOME/.vimrc";
-cat $SNAP_REAL_HOME/.vimrc;
-inotifywait -e modify $SNAP_REAL_HOME/.vimrc;
+cat $USER_HOME/.vimrc;
+inotifywait -e modify $USER_HOME/.vimrc;
   
-if ([ -f $SNAP_REAL_HOME/.bashrc ] && ( ! grep -qR 'alias ssh="ssh -F $SNAP_REAL_HOME/.ssh/viSSHous"' $SNAP_REAL_HOME/.bashrc ));
-  then echo 'alias ssh="ssh -F $SNAP_REAL_HOME/.ssh/viSSHous"' >> $SNAP_REAL_HOME/.bashrc && bash
+if ([ -f $USER_HOME/.bashrc ] && ( ! grep -qR 'alias ssh="ssh -F $USER_HOME/.ssh/viSSHous"' $USER_HOME/.bashrc ));
+  then echo 'alias ssh="ssh -F $USER_HOME/.ssh/viSSHous"' >> $USER_HOME/.bashrc && bash
 fi
 
-if ([ -f $SNAP_REAL_HOME/.zshrc ] && ( ! grep -qR 'alias ssh="ssh -F $SNAP_REAL_HOME/.ssh/viSSHous"' $SNAP_REAL_HOME/.zshrc ));
-  then echo 'alias ssh="ssh -F $SNAP_REAL_HOME/.ssh/viSSHous"' >> $SNAP_REAL_HOME/.zshrc && zsh
+if ([ -f $USER_HOME/.zshrc ] && ( ! grep -qR 'alias ssh="ssh -F $USER_HOME/.ssh/viSSHous"' $USER_HOME/.zshrc ));
+  then echo 'alias ssh="ssh -F $USER_HOME/.ssh/viSSHous"' >> $USER_HOME/.zshrc && zsh
 fi 
 
-echo "# last updated: $(date)" > $SNAP_REAL_HOME/.ssh/viSSHous
-echo 'Include ~/.ssh/config' >> $SNAP_REAL_HOME/.ssh/viSSHous
-echo "SetEnv LC_MONETARY=$(cat ~/.vimrc | base64)" >> $SNAP_REAL_HOME/.ssh/viSSHous
-echo 'RemoteCommand mkdir -p ~/.vim; echo $LC_MONETARY > ~/.vim/visshnu; base64 --decode ~/.vim/visshnu > ~/.vimrc; echo "😈 [LOG] VimRC was configured successfully"; if ( ! command -v vim &> /dev/null ); then echo "👿 [WARN] Vim not found"; sudo apt-get install vim -y &> /dev/null; if [ $? != 0 ]; then echo "👿 [WARN] Vim could not be auto-installed. Try manually with \`sudo apt-get install vim -y \`"; else echo "😈 [RESOLVED] Vim was auto-installed successfully"; fi; fi; if ( grep -qR "plug#begin" ~/.vimrc); then set vimplug=true; echo "😈 [LOG] Plugin manager detected: Vim-Plug"; fi; if ( grep -qR "plugin#begin" ~/.vimrc); then set vundle=true; echo "😈 Plugin manager detected: Vundle"; fi; if ([ -z $vimplug ] && [ ! -f ~/.vim/autoload/plug.vim ]); then curl -sfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim; if [ $? == 0 ]; then echo "😈 [LOG] Vim-Plug was auto-installed successfully"; fi; fi; if (( [ -z $vimplug ] || [ -z $vundle ]) && ( ! command -v git &> /dev/null )); then echo "👿 [WARN] Git not detected, but required by plugin manager."; sudo apt-get install git -y &> /dev/null; if [ $? != 0 ]; then echo "👿 [WARN] Git could not be auto-installed. Try manually with \`sudo apt-get install git\`"; else echo "😈 [RESOLVED] Git was auto-installed successfully"; fi; fi; if ( [ -z $vimplug ] && [ -f ~/.vim/autoload/plug.vim ] ) ; then echo "😈 [LOG] Installing/updating plugins with Vim-Plug"; yes | vim -c ":PlugInstall | quit! | quit!" &> /dev/null; fi; echo "😈 [LOG] viSSHous setup complete"; bash' >> $SNAP_REAL_HOME/.ssh/viSSHous
-echo "RequestTTY yes" >> $SNAP_REAL_HOME/.ssh/viSSHous
+echo "# last updated: $(date)" > $USER_HOME/.ssh/viSSHous
+echo 'Include ~/.ssh/config' >> $USER_HOME/.ssh/viSSHous
+echo "SetEnv LC_MONETARY=$(cat ~/.vimrc | base64)" >> $USER_HOME/.ssh/viSSHous
+echo 'RemoteCommand mkdir -p ~/.vim; echo $LC_MONETARY > ~/.vim/visshnu; base64 --decode ~/.vim/visshnu > ~/.vimrc; echo "😈 [LOG] VimRC was configured successfully"; if ( ! command -v vim &> /dev/null ); then echo "👿 [WARN] Vim not found"; sudo apt-get install vim -y &> /dev/null; if [ $? != 0 ]; then echo "👿 [WARN] Vim could not be auto-installed. Try manually with \`sudo apt-get install vim -y \`"; else echo "😈 [RESOLVED] Vim was auto-installed successfully"; fi; fi; if ( grep -qR "plug#begin" ~/.vimrc); then set vimplug=true; echo "😈 [LOG] Plugin manager detected: Vim-Plug"; fi; if ( grep -qR "plugin#begin" ~/.vimrc); then set vundle=true; echo "😈 Plugin manager detected: Vundle"; fi; if ([ -z $vimplug ] && [ ! -f ~/.vim/autoload/plug.vim ]); then curl -sfLo ~/.vim/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim; if [ $? == 0 ]; then echo "😈 [LOG] Vim-Plug was auto-installed successfully"; fi; fi; if (( [ -z $vimplug ] || [ -z $vundle ]) && ( ! command -v git &> /dev/null )); then echo "👿 [WARN] Git not detected, but required by plugin manager."; sudo apt-get install git -y &> /dev/null; if [ $? != 0 ]; then echo "👿 [WARN] Git could not be auto-installed. Try manually with \`sudo apt-get install git\`"; else echo "😈 [RESOLVED] Git was auto-installed successfully"; fi; fi; if ( [ -z $vimplug ] && [ -f ~/.vim/autoload/plug.vim ] ) ; then echo "😈 [LOG] Installing/updating plugins with Vim-Plug"; yes | vim -c ":PlugInstall | quit! | quit!" &> /dev/null; fi; echo "😈 [LOG] viSSHous setup complete"; bash' >> $USER_HOME/.ssh/viSSHous
+echo "RequestTTY yes" >> $USER_HOME/.ssh/viSSHous
